{
 "title": "Nomad",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Client Consul Check Registrations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_consul_check_registrations",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Client Allocations Running",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_allocations_running",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Client Allocations Blocked",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_allocations_blocked",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Runtime Total GS Pauses",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "nomad_runtime_total_gc_pause_ns"
    }
   ]
  },
  {
   "title": "Runtime Alloc Bytes (Linux)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nomad_runtime_alloc_bytes", "legendFormat": "{{host}}" }
   ]
  }
 ]
}